name: linting, testing, building
on: 
  push: 
    branches: [main]
  pull_requests:
    branches: [main]
jobs:
  pipeline: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{matring.node-version}}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{matrix.node-version}}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: unit testing
        run: npm run test:unit