name: linting, testing, building
on: 
  push: 
    branches: [main]
  pull_requests:
    branches: [main]
jobs:
  pipeline: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]